# Generated by Django 3.0.5 on 2020-04-07 11:20

import DjangoUeditor.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200407_1026'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '用户评论', 'verbose_name_plural': '用户评论'},
        ),
        migrations.AlterModelOptions(
            name='vote',
            options={'verbose_name': '用户投票', 'verbose_name_plural': '用户投票'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='评论内容'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_ip',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='用户IP'),
        ),
    ]
