# Generated by Django 3.0.5 on 2020-04-09 09:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0005_auto_20200408_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='user_vote',
            field=models.ManyToManyField(blank=True, related_name='user_vote_answer', to=settings.AUTH_USER_MODEL),
        ),
    ]
