# Generated by Django 3.0.5 on 2020-04-10 14:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_article_user_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='dislike_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='like_counts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_vote',
            field=models.ManyToManyField(blank=True, related_name='user_vote_article', to=settings.AUTH_USER_MODEL),
        ),
    ]
