# Generated by Django 3.0.5 on 2020-04-15 10:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_auto_20200410_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.CharField(default='.........', max_length=200, verbose_name='文章简介'),
        ),
        migrations.AlterField(
            model_name='article',
            name='comment_counts',
            field=models.IntegerField(default=0, verbose_name='评论数'),
        ),
        migrations.AlterField(
            model_name='article',
            name='dislike_counts',
            field=models.IntegerField(default=0, verbose_name='踩'),
        ),
        migrations.AlterField(
            model_name='article',
            name='like_counts',
            field=models.IntegerField(default=0, verbose_name='赞'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user_vote',
            field=models.ManyToManyField(blank=True, related_name='user_vote_article', to=settings.AUTH_USER_MODEL, verbose_name='喜欢文章的人'),
        ),
    ]
